let products=[],settings={};const $=id=>document.getElementById(id);
async function api(url,opt={}){const headers={...(opt.headers||{})};if(!(opt.body instanceof FormData)&&opt.body!==undefined)headers['Content-Type']='application/json';const r=await fetch(url,{...opt,headers});const d=await r.json();if(!r.ok)throw new Error(d.error||'Ошибка');return d}
async function check(){try{let d=await api('/api/me');if(d.ok){$('login').classList.add('hidden');$('app').classList.remove('hidden');load()}}catch(e){}}
$('loginBtn').onclick=async()=>{try{await api('/api/login',{method:'POST',body:JSON.stringify({password:$('pass').value})});$('login').classList.add('hidden');$('app').classList.remove('hidden');load()}catch(e){$('loginErr').textContent=e.message}};
$('pass').addEventListener('keydown',e=>{if(e.key==='Enter')$('loginBtn').click()});
$('logout').onclick=async()=>{await api('/api/logout',{method:'POST'});location.reload()};
document.querySelectorAll('.tab').forEach(t=>t.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));t.classList.add('active');['products','orders','settings'].forEach(x=>$(x+'Tab').classList.add('hidden'));$(t.dataset.tab+'Tab').classList.remove('hidden');if(t.dataset.tab==='orders')loadOrders();if(t.dataset.tab==='settings')renderSettings()});
async function load(){products=await api('/api/products');settings=await api('/api/settings');renderProducts()}
function renderProducts(){let el=$('productList');el.innerHTML=products.map((p,i)=>`<div class="product-edit">
<img src="${p.image}" onerror="this.src='data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 width=%22150%22 height=%22190%22><rect width=%22100%%22 height=%22100%%22 fill=%22%23eee%22/><text x=%2250%%22 y=%2250%%22 text-anchor=%22middle%22>Фото</text></svg>'">
<div><div class="fields">
<input class="wide" data-k="name" value="${esc(p.name)}" placeholder="Название">
<input data-k="article" value="${esc(p.article)}" placeholder="Артикул">
<input data-k="category" value="${esc(p.category)}" placeholder="Категория">
<input data-k="price" type="number" value="${p.price||''}" placeholder="Цена, грн">
<input class="wide" data-k="description" value="${esc(p.description)}" placeholder="Описание">
<input class="wide" data-k="sizes" value="${(p.sizes||[]).join(', ')}" placeholder="Размеры через запятую: 42, 44, 46">
</div><div class="actions"><label class="upload">📷 Фото <input hidden type="file" accept="image/*" data-photo="${i}"></label><button class="save" onclick="saveProduct(${i})">Сохранить</button><button class="danger" onclick="deleteProduct(${i})">Удалить</button></div></div></div>`).join('')||'<p>Товаров пока нет.</p>';
el.querySelectorAll('input[type=file]').forEach(x=>x.onchange=()=>uploadPhoto(Number(x.dataset.photo),x.files[0]));
}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
window.saveProduct=async i=>{const box=$('productList').children[i],p=products[i];box.querySelectorAll('[data-k]').forEach(x=>{let k=x.dataset.k;p[k]=k==='price'?Number(x.value)||0:k==='sizes'?x.value.split(',').map(s=>s.trim()).filter(Boolean):x.value});await api('/api/products/save',{method:'POST',body:JSON.stringify({products})});alert('Товар сохранён ♡');load()};
window.deleteProduct=async i=>{if(!confirm('Удалить товар?'))return;products.splice(i,1);await api('/api/products/save',{method:'POST',body:JSON.stringify({products})});renderProducts()};
$('addProduct').onclick=async()=>{products.push({id:Date.now(),article:'',name:'Новый товар',category:'Одежда',price:0,sizes:['42','44','46','48'],description:'',image:'images/product-1.png',active:true});await api('/api/products/save',{method:'POST',body:JSON.stringify({products})});renderProducts()};
async function uploadPhoto(i,file){if(!file)return;try{const fd=new FormData();fd.append('file',file);let d=await api('/api/upload',{method:'POST',body:fd});products[i].image=d.image;await api('/api/products/save',{method:'POST',body:JSON.stringify({products})});renderProducts()}catch(e){alert(e.message)}}
async function loadOrders(){let os=await api('/api/orders');$('orders').innerHTML=os.reverse().map(o=>`<div class="order"><div class="order-top"><b>Заказ #${o.id}</b><small>${esc(o.date)}</small></div><p><b>${esc(o.name)}</b> • <a href="tel:${esc(o.phone)}">${esc(o.phone)}</a></p><p>📦 <b>${esc(o.delivery)}</b>${o.city?' • Город: '+esc(o.city):''}${o.branch?' • Отделение: '+esc(o.branch):''}<br>💳 <b>${esc(o.payment)}</b></p><div class="order-items">${(o.items||[]).map(x=>`<div class="order-product"><img src="${esc(x.image||'')}" onerror="this.style.display='none'"><div><b>${esc(x.name)}</b><br><small>Артикул: ${esc(x.article||'—')} • Размер: ${esc(x.size)} • Кол-во: ${esc(x.qty||1)}${x.price?' • '+Number(x.price).toLocaleString('uk-UA')+' грн':''}</small></div></div>`).join('')}</div><small>Комментарий: ${esc(o.comment||'—')}</small><br><button class="danger" onclick="delOrder('${o.id}')">Удалить</button></div>`).join('')||'<p>Заказов пока нет.</p>'}
window.delOrder=async id=>{if(confirm('Удалить заказ?')){await api('/api/orders/delete',{method:'POST',body:JSON.stringify({id})});loadOrders()}};
$('refreshOrders').onclick=loadOrders;
function renderSettings(){$('settingsForm').innerHTML=`<label>Название<input name="shopName" value="${esc(settings.shopName)}"></label><label>Подпись<input name="tagline" value="${esc(settings.tagline)}"></label><label>Телефон Елены<input name="phone" value="${esc(settings.phone)}"></label><label>Имя Елены<input name="phoneName" value="${esc(settings.phoneName)}"></label><label class="wide">Ссылка на Telegram<input name="telegram" value="${esc(settings.telegram)}" placeholder="https://t.me/..."></label><label class="wide">Ссылка на Viber<input name="viber" value="${esc(settings.viber)}" placeholder="viber://chat?number=..."></label><label>Телефон Светланы<input name="phone2" value="${esc(settings.phone2)}"></label><label>Имя Светланы<input name="phone2Name" value="${esc(settings.phone2Name)}"></label><label class="wide">Адрес<input name="address" value="${esc(settings.address)}"></label><label class="wide">Доставка<textarea name="deliveryNote">${esc(settings.deliveryNote)}</textarea></label><label class="wide">Самовывоз<textarea name="pickupNote">${esc(settings.pickupNote)}</textarea></label><button type="submit">Сохранить настройки</button>`}
$('settingsForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);settings=Object.fromEntries(f.entries());await api('/api/settings/save',{method:'POST',body:JSON.stringify(settings)});alert('Настройки сохранены ♡')};
$('changePass').onclick=async()=>{if($('newPass').value.length<4)return alert('Минимум 4 символа');await api('/api/password',{method:'POST',body:JSON.stringify({password:$('newPass').value})});$('newPass').value='';alert('Пароль изменён')};
check();
