name = "paradiso-italy"
main = "worker.js"
compatibility_date = "2026-09-30"

[assets]
directory = "./public"
binding = "ASSETS"
run_worker_first = ["/api/*"]

[[d1_databases]]
binding = "DB"
database_name = "paradiso-italy-db"
database_id = "2d231323-e95e-4189-8b0a-816168919e57"
